config/routes.rb
Dothisnow::Application.routes.draw do
  #root :to => "hello#index"

  get "/" => redirect("/tasks"), :as => :home_path

  get "/sign_in", :to => "hello#index", :as => :sign_in_path
  post "/sign_in/login", :to => "hello#login"
  get "/sign_in/login" => redirect("/sign_in")
  get "/logout", :to => "hello#logout", :as => :logout_path
  
  get "/tasks/:id/move_up", :to => "tasks#move_up", :as => :move_up
  get "/tasks/:id/move_down", :to => "tasks#move_down", :as => :move_down
  get "/tasks/:id/toggle", :to => "tasks#toggle_status", :as => :toggle_status
  match "/tasks/add-task-list", :to => "tasks#new_from_list", :as => :new_task_list_path
  get "/tasks/do", :to => "tasks#do_tasks", :as => :do_tasks
  
  resources :tasks
  resources :users

end

app/models/task.rb
class Task < ActiveRecord::Base

  def done?
    done != 0
  end
  
  def move_task(direction = :up)
  
    #selection of the task which priority will be replaced
    selectPriority = direction == :up ? "priority < ?" : "priority > ?"
    order = direction == :up ? "priority DESC" : "priority"
  
    Task.transaction do
      task_to_replace = Task.where(:user_id => user_id).where(selectPriority, priority).order(order).first
      if task_to_replace
        this_task = Task.where(:id => id).first
        
        old_priority = task_to_replace.priority
        task_to_replace.priority = priority      
        this_task.priority = old_priority
        
        this_task.save
        task_to_replace.save
      end  
    end       
  end
  
  def move_up
    move_task(:up)
  end
  
  def move_down
    move_task(:down)
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  validates :email, :format => { :with => /^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$/i }
  validates :password, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  before_filter :authenticate!

  helper_method :current_user, :is_admin?, :signed_in?

  def signed_in?
   !!current_user
  end

  def current_user
    @current_user ||= User.where(:id => session[:user_id]).first if session[:user_id]
  end
  
  def is_admin?
    session[:user_is_admin] == 1
  end

  def authenticate!
    flash[:error] = "You must authenticate to pass this point."
    redirect_to :sign_in_path unless signed_in?
  end
  
  def authorize_admin!
    flash[:error] = "Unauthorized access. Please authenticate."
    redirect_to :sign_in_path unless is_admin?
  end

end

app/controllers/hello_controller.rb
class HelloController < ApplicationController

  skip_before_filter :authenticate!
  
  def login
  
    user = User.where(:email => params[:email], :password => params[:password]).first
    
    if user 
      session[:user_id] = user.id 
      session[:user_is_admin] = user.is_admin
      redirect_to :home_path
    else
      flash[:error] = "Incorrect credentials!"
      redirect_to :sign_in_path
    end  
      
  end
  
  def logout
  
    session[:user_id] = nil
    session[:user_is_admin] = nil
    redirect_to :sign_in_path
  
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.order(:priority).where(:user_id => current_user.id).all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tasks }
    end
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
    @task = Task.where(:id => params[:id], :user_id => current_user.id).first

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @task }
    end
  end

  # GET /tasks/new
  # GET /tasks/new.json
  def new
    @task = Task.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @task }
    end
  end
  
  def new_from_list
    if params[:list]
      params[:list].split(/\n/).each do |task|
        task = task.strip
        if task.length > 0
          t = Task.new(:title => task, :user_id => current_user.id, :done => 0)
          t.save
          t.priority = t.id
          t.save
        end
      end       
      redirect_to :tasks, :notice => "Your task list has been saved"
    else  
      render "new_task_list.html.erb"
    end  
  end
  
  def do_tasks
    if params[:done]
      task = Task.where(:user_id => current_user.id, :id => params[:done]).first
      task.done = 1
      task.save
    end  
  
    @task = Task.where(:user_id => current_user.id, :done => 0).order(:priority).first
  end

  # GET /tasks/1/edit
  def edit
    @task = Task.where(:id => params[:id], :user_id => current_user.id).first
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(params[:task])

    respond_to do |format|
      if @task.save
        @task.priority = @task.id and @task.user_id = current_user.id and @task.save
         
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render json: @task, status: :created, location: @task }
      else
        format.html { render action: "new" }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tasks/1
  # PUT /tasks/1.json
  def update
    @task = Task.where(:id => params[:id], :user_id => current_user.id).first

    respond_to do |format|
      if @task.update_attributes(params[:task])
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task = Task.where(:id => params[:id], :user_id => current_user.id).first
    @task.destroy

    respond_to do |format|
      format.html { redirect_to tasks_url }
      format.json { head :no_content }
    end
  end
  
  def move_down
    @task = Task.where(:id => params[:id], :user_id => current_user.id).first
    @task.move_down
    
    redirect_to :tasks  
  end
  
  def move_up
    @task = Task.where(:id => params[:id], :user_id => current_user.id).first
    @task.move_up
    @task.save  
    
    redirect_to :tasks
  end
  
  def toggle_status
    @task = Task.where(:id => params[:id], :user_id => current_user.id).first
    @task.done = @task.done==0 ? 1 : 0
    @task.save  
    
    redirect_to :tasks
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_filter :authorize_admin!

  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hello_helper.rb
module HelloHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/hello/index.html.erb
<h1>Hello, Anonymous</h1>
<p>Sign in, please!</p>

<% flash.each do |key, msg| %>
  <%= content_tag :div, msg, :class => [key, " message"], :id => "notice_ #{key}" %>
  <%= content_tag :script, :type => "text/javascript" do -%>
    setTimeout("new Effect.Fade('notice_<%= key %>');", 15000);
  <% end %>
<% end %>

<%= form_tag "sign_in/login" do %>
  <%= label_tag :email, "E-mail" %>
  <%= email_field_tag :email, "@" %><br>
  <%= label_tag :password, "Password" %>
  <%= password_field_tag :password %><br>
  <%= submit_tag "Lets go get 'em!", :class => "btn-primary" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Do this now!</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <%= link_to "Do this now!", :home_path, :class => "brand" %>
      <div class="nav-collapse">
        <ul class="nav">
          <li><%= link_to "Login", :sign_in_path unless signed_in? %></li>
          <li><%= link_to "Tasks", :tasks if signed_in? %></li>
          <li><%= link_to "New task list", :new_task_list_path if signed_in? %></li>
          <li><%= link_to "Users", :users if is_admin? %></li>
          <li><%= link_to "Logout", :logout_path if signed_in? %></li>
        </ul>  
      </div>
    </div>  
  </div>  
</div>

<div class="container">
  <%= yield %>

  <br><br>
  <hr>
  <footer>
    <p>
      <a rel="license" href="http://creativecommons.org/licenses/by/3.0/cz/">
        <img alt="Creative Commons License" style="border-width:0" src="http://i.creativecommons.org/l/by/3.0/cz/88x31.png" />
      </a>Copyleft 2012, Temistokles
    </p>
  </footer>
</div>  


</body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% if @task.id %>
    <div class="field">
      <%= f.label :priority %>
      <%= f.number_field :priority %>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :done %>
    <%= f.check_box :done %>
  </div>
  <div class="actions">
    <%= f.submit :class => "btn-primary" %>
  </div>
<% end %>

app/views/tasks/do_task.html.erb
<h1>Handle this, now!</h1>

<p>
  <b>Title:</b>
  <%= @task.title %>
</p>

<%= link_to 'Done. Next one!', do_tasks_url(:done => @task.id), :class => "btn-primary" %>

<br><br>

<%= link_to 'Back', tasks_path, :class => "btn" %>

app/views/tasks/do_tasks.html.erb
<h1>Handle this, now!</h1>

<% if @task %>
  <p>
    <b>Title:</b>
    <%= @task.title %>
  </p>

  <br><br>

  <%= link_to 'Done. Next one!', do_tasks_url(:done => @task.id), :class => "btn btn-primary" %>

<% else %>

  <p>No tasks left, bro. Create some.</p>
  <br><br>
  
  <%= link_to raw('New <b>Task List</b>'), :new_task_list_path, :class => "btn btn-primary" %>
  <%= link_to 'New Task', new_task_path, :class => "btn btn-primary" %>

<% end %>

<br><br>

<%= link_to 'Back To Tasks', tasks_path, :class => "btn" %>

app/views/tasks/edit.html.erb
<h1>Editing task</h1>

<%= render 'form' %>

<%= link_to 'Show', @task, :class => "btn" %>
<%= link_to 'Back', tasks_path, :class => "btn" %>

app/views/tasks/index.html.erb
<h1>Listing current tasks</h1>

<table class="listing">
  <thead>
    <th colspan="2">Priority</th>
    <th>Title</th>
    <th>Done</th>
    <th colspan="3">Actions</th>
  </thead>

<% @tasks.each do |task| %>
  <tr <%= raw('class="done"') if task.done? %>>
    <td><%= link_to "[UP]", move_up_url(:id => task.id), :remote => true, :class => "move_up" %></td>
    <td><%= link_to "[DOWN]", move_down_url(:id => task.id), :remote => true, :class => "move_down" %></td>
    <td><%= task.title %></td>
    <td class="task-status">
      <%= link_to_if(task.done?, raw('<img src="/images/done.png" alt="[YES]" title="Yes">'),
                     toggle_status_url(:id => task.id), :remote => true, :class => "toggle_status" ) do
                       link_to(raw('<img src="/images/pending.png" alt="[NO]" title="No">'),
                       toggle_status_url(:id => task.id), :remote => true, :class => "toggle_status" )
          end
      %>    
    </td>
    <td><%= link_to 'Show', task %></td>
    <td><%= link_to 'Edit', edit_task_path(task) %></td>
    <td><%= link_to 'Destroy', task, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to "Bring dem Tasks on!", :do_tasks, :class => "btn btn-primary" %>

<br><br>

<%= link_to 'Le new Task', new_task_path, :class => "btn" %>
<%= link_to 'Le new Task List', :new_task_list_path, :class => "btn" %>

app/views/tasks/new.html.erb
<h1>New task</h1>

<%= render 'form' %>

<%= link_to 'Back', tasks_path, :class => "btn" %>

app/views/tasks/new_task_list.html.erb
<h1>Create new task list</h1>

<%= form_tag do %>
<p>Separate each task with a new line.</p>
<%= text_area_tag :list, "task1\ntask2", :class => "task-list", :onclick => "this.select()" %><br> 
<%= submit_tag "Create 'em!", :class => "btn-primary" %>
<% end %>

<br />

<%= link_to 'Back', :tasks, :class => "btn" %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Priority:</b>
  <%= @task.priority %>
</p>

<p>
  <b>Title:</b>
  <%= @task.title %>
</p>

<p>
  <b>Done:</b>
  <%= @task.done %>
</p>


<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email, "E-mail" %>
    <%= f.email_field :email %><br>

    <%= f.label :password, "Password" %>
    <%= f.password_field :password %><br>
    
    <%= f.label :is_admin, "Is admin" %>
    <%= f.check_box :is_admin %>
  </div>
  <div class="actions">
    <%= f.submit :class => 'btn-primary' %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user, :class => "btn" %>
<%= link_to 'Back', users_path, :class => "btn" %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table class="listing">
  <tr>
    <th>E-mail</th>
    <th colspan="3">Actions</th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.email %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path, :class => "btn" %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path, :class => "btn" %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>E-mail:</b>
  <%= @user.email %>
</p>


<%= link_to 'Edit', edit_user_path(@user), :class => "btn" %>
<%= link_to 'Back', users_path, :class => "btn" %>